name: ZeFreeze
version: 1.1.2
author: ZeTioZ
main: fr.zetioz.zefreeze.ZeFreezeMain
commands:
  zefreeze:
    aliases: [frz, freeze, zfrz, zfreeze]
    description: ZeFreeze main command
  zeunfreeze:
    aliases: [unfrz, unfreeze, zunfrz, zunfreeze]
    description: ZeFreeze unfreeze command