name: OpsyFreeze
version: 0.3.0
author: ZeTioZ
main: fr.zetioz.opsyfreeze.OpsyFreezeMain
commands:
  opsyfreeze:
    aliases: [frz, freeze, ofrz, ofreeze]
    description: OpsyFreeze main command
  opsyunfreeze:
    aliases: [unfrz, unfreeze, ounfrz, ounfreeze]
    description: OpsyFreeze unfreeze command